-- CivicFix production-style Supabase schema for PS-18.
-- Run in Supabase SQL Editor. Review policies before a real municipal deployment.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'citizen' check (role in ('citizen','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  ticket_code text unique not null default ('CF-' || floor(random()*9000 + 1000)::text),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text not null,
  category text not null,
  address text,
  lat double precision not null,
  lng double precision not null,
  photo_path text,
  priority_score integer not null default 35 check (priority_score between 0 and 100),
  severity text not null default 'Low' check (severity in ('Low','Medium','High')),
  status text not null default 'New' check (status in ('New','Verified','Assigned','In Progress','Resolved','Reopened')),
  verified boolean not null default false,
  duplicate_group_id uuid,
  sla_due_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.complaint_events (
  id bigint generated by default as identity primary key,
  complaint_id bigint not null references public.complaints(id) on delete cascade,
  status text not null,
  note text,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.complaint_feedback (
  id bigint generated by default as identity primary key,
  complaint_id bigint not null references public.complaints(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  resolved boolean not null,
  rating integer check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists public.duplicate_groups (
  id uuid primary key default gen_random_uuid(),
  canonical_complaint_id bigint references public.complaints(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.complaints add constraint complaints_duplicate_group_fk foreign key (duplicate_group_id) references public.duplicate_groups(id) on delete set null;

create index if not exists complaints_priority_idx on public.complaints(priority_score desc);
create index if not exists complaints_status_idx on public.complaints(status);
create index if not exists complaints_user_idx on public.complaints(user_id);
create index if not exists complaints_location_idx on public.complaints(lat,lng);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name','')) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin(uid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id=uid and role='admin');
$$;

alter table public.profiles enable row level security;
alter table public.complaints enable row level security;
alter table public.complaint_events enable row level security;
alter table public.complaint_feedback enable row level security;
alter table public.duplicate_groups enable row level security;

-- Profiles: users can read/update their own profile; admins can read all.
drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin(auth.uid()));
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update to authenticated using (id=auth.uid());

-- Complaints: citizens see their own records; admins manage all.
drop policy if exists complaints_select on public.complaints;
create policy complaints_select on public.complaints for select to authenticated using (user_id=auth.uid() or public.is_admin(auth.uid()));
drop policy if exists complaints_insert on public.complaints;
create policy complaints_insert on public.complaints for insert to authenticated with check (user_id=auth.uid());
drop policy if exists complaints_update on public.complaints;
create policy complaints_update on public.complaints for update to authenticated using (user_id=auth.uid() or public.is_admin(auth.uid())) with check (user_id=auth.uid() or public.is_admin(auth.uid()));

-- Status history: citizens can read history for their complaints; admins can insert/read all.
drop policy if exists events_select on public.complaint_events;
create policy events_select on public.complaint_events for select to authenticated using (exists(select 1 from public.complaints c where c.id=complaint_id and (c.user_id=auth.uid() or public.is_admin(auth.uid()))));
drop policy if exists events_insert on public.complaint_events;
create policy events_insert on public.complaint_events for insert to authenticated with check (public.is_admin(auth.uid()));

-- Feedback: citizens may submit their own feedback on their complaint.
drop policy if exists feedback_insert on public.complaint_feedback;
create policy feedback_insert on public.complaint_feedback for insert to authenticated with check (user_id=auth.uid() and exists(select 1 from public.complaints c where c.id=complaint_id and c.user_id=auth.uid()));
drop policy if exists feedback_select on public.complaint_feedback;
create policy feedback_select on public.complaint_feedback for select to authenticated using (user_id=auth.uid() or public.is_admin(auth.uid()));

-- Storage: create a bucket named complaint-images in Dashboard first.
-- Then add Storage policies limiting uploads to the authenticated user's folder.
-- Example path: <auth.uid()>/<ticket-code>-filename.jpg
