import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import "./index.css";
const API="http://localhost:5000/api";

function App(){
 const [issues,setIssues]=useState([]),[stats,setStats]=useState({total:0,reported:0,inProgress:0,resolved:0});
 const [page,setPage]=useState("home"),[search,setSearch]=useState(""),[filter,setFilter]=useState("All"),[message,setMessage]=useState("");
 async function load(){try{const[a,b]=await Promise.all([fetch(API+"/issues"),fetch(API+"/stats")]);setIssues(await a.json());setStats(await b.json())}catch{setMessage("Backend is not running. Start it with: cd backend then npm start")}}
 useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());try{const r=await fetch(API+"/issues",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const x=await r.json();if(!r.ok)throw Error(x.error);e.target.reset();setMessage("Issue reported successfully!");await load();setPage("issues")}catch(x){setMessage(x.message)}}
 async function vote(id){await fetch(`${API}/issues/${id}/vote`,{method:"POST"});load()}
 async function status(id,s){await fetch(`${API}/issues/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:s})});load()}
 const shown=issues.filter(i=>`${i.title} ${i.description} ${i.location} ${i.category}`.toLowerCase().includes(search.toLowerCase())&&(filter==="All"||i.status===filter));
 return <><header><div className="brand" onClick={()=>setPage("home")}>🏙️ CivicFix</div><nav><button onClick={()=>setPage("home")}>Home</button><button onClick={()=>setPage("report")}>Report Issue</button><button onClick={()=>setPage("issues")}>Community Issues</button><button onClick={()=>setPage("admin")}>Admin</button></nav></header>
 {message&&<div className="notice">{message}<button onClick={()=>setMessage("")}>×</button></div>}
 {page==="home"&&<><main className="hero"><div><p className="eyebrow">SMARTER COMMUNITIES</p><h1>Report problems.<br/><span>Improve your city.</span></h1><p className="lead">CivicFix helps citizens report local problems and track progress toward safer, cleaner neighborhoods.</p><button className="primary" onClick={()=>setPage("report")}>Report an Issue</button> <button className="secondary" onClick={()=>setPage("issues")}>View Issues</button></div><div className="heroCard">🏘️<h2>Your voice matters</h2><p>Every report helps make local services more visible and accountable.</p></div></main><section className="stats"><Stat v={stats.total} t="Total Reports"/><Stat v={stats.reported} t="Reported"/><Stat v={stats.inProgress} t="In Progress"/><Stat v={stats.resolved} t="Resolved"/></section><section className="features"><Feature i="📢" t="Easy Reporting" d="Submit a civic issue in a few simple steps."/><Feature i="🤝" t="Community Voting" d="Support issues that matter to your neighborhood."/><Feature i="📊" t="Transparent Tracking" d="See issue status from report to resolution."/></section></>}
 {page==="report"&&<main className="page"><p className="eyebrow">CITIZEN REPORT</p><h1 className="smallTitle">Report a Civic Issue</h1><form className="form" onSubmit={submit}><label>Issue title<input name="title" placeholder="e.g. Broken street light" required/></label><label>Description<textarea name="description" rows="5" placeholder="Describe the problem..." required/></label><div className="two"><label>Category<select name="category" required><option value="">Select</option><option>Road</option><option>Street Light</option><option>Garbage</option><option>Water</option><option>Public Safety</option><option>Other</option></select></label><label>Location<input name="location" placeholder="Area / landmark" required/></label></div><label>Your name (optional)<input name="reportedBy" placeholder="Anonymous"/></label><button className="primary">Submit Report</button></form></main>}
 {page==="issues"&&<main className="page"><p className="eyebrow">COMMUNITY</p><h1 className="smallTitle">Community Issues</h1><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search issues..."/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Reported</option><option>In Progress</option><option>Resolved</option></select></div><div className="grid">{shown.map(i=><article className="card" key={i.id}><div className="row"><b className="badge">{i.status}</b><span>#{i.id}</span></div><h2>{i.title}</h2><p>{i.description}</p><small>📍 {i.location} • 🏷️ {i.category}</small><div className="row bottom"><span>👍 {i.votes} votes</span><button onClick={()=>vote(i.id)}>Support</button></div></article>)}</div></main>}
 {page==="admin"&&<main className="page"><p className="eyebrow">MANAGEMENT</p><h1 className="smallTitle">Admin Dashboard</h1><div className="admin">{issues.map(i=><div className="adminRow" key={i.id}><div><b>{i.title}</b><small>{i.category} • {i.location}</small></div><select value={i.status} onChange={e=>status(i.id,e.target.value)}><option>Reported</option><option>In Progress</option><option>Resolved</option></select></div>)}</div></main>}
 <footer>CivicFix © 2026 • Built for safer & smarter communities</footer></>
}
const Stat=({v,t})=><div className="stat"><b>{v}</b><span>{t}</span></div>;
const Feature=({i,t,d})=><div className="feature"><div>{i}</div><h2>{t}</h2><p>{d}</p></div>;
createRoot(document.getElementById("root")).render(<App/>);
